/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    pages: Page;
    cases: Case;
    posts: Post;
    services: Service;
    faqs: Faq;
    applications: Application;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
    faq: Faq1;
    blog: Blog;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Должен совпадать с названием папки в app/(site) (например: about-us, prices, portfolio и т.д.)
   */
  slug: string;
  description?: string | null;
  sections?:
    | (
        | {
            blockId: string;
            subtitle: string;
            description: string;
            stamps?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            backgroundImage: number | Media;
            image: number | Media;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            blockId: string;
            subtitle: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            blockId: string;
            projectTitle: string;
            projectDescription: string;
            client: string;
            status: string;
            caseTitle: string;
            caseDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutProjectSection';
          }
        | {
            blockId: string;
            contentTitle: string;
            contentItems?:
              | {
                  text: string;
                  anchorId: string;
                  id?: string | null;
                }[]
              | null;
            clientImage: number | Media;
            clientImageDescription: string;
            clientTitle: string;
            clientSubtitle: string;
            clientDescription: string;
            layoutImage: number | Media;
            layoutImageDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clientSection';
          }
        | {
            blockId: string;
            title: string;
            description: string;
            strategyTitle: string;
            strategyItems?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            conclusion: string;
            strategyImage: number | Media;
            imageDescription: string;
            processTitle: string;
            processDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'strategySection';
          }
        | {
            blockId: string;
            title: string;
            description: string;
            goals?:
              | {
                  title: string;
                  description: string;
                  isLight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'goalsSection';
          }
        | {
            blockId: string;
            title: string;
            subtitle: string;
            tasks?:
              | {
                  text: string;
                  isLight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'businessSection';
          }
        | {
            blockId: string;
            authorImage: number | Media;
            authorName: string;
            authorRole: string;
            authorDescription?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'authorSection';
          }
      )[]
    | null;
  showPortfolio?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  path: string;
  slug: string;
  tags?: (number | Tag)[] | null;
  sections?:
    | (
        | {
            blockId: string;
            subtitle: string;
            description: string;
            stamps?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            backgroundImage: number | Media;
            image: number | Media;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            blockId: string;
            subtitle: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            blockId: string;
            projectTitle: string;
            projectDescription: string;
            client: string;
            status: string;
            caseTitle: string;
            caseDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutProjectSection';
          }
        | {
            blockId: string;
            contentTitle: string;
            contentItems?:
              | {
                  text: string;
                  anchorId: string;
                  id?: string | null;
                }[]
              | null;
            clientImage: number | Media;
            clientImageDescription: string;
            clientTitle: string;
            clientSubtitle: string;
            clientDescription: string;
            layoutImage: number | Media;
            layoutImageDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clientSection';
          }
        | {
            blockId: string;
            title: string;
            description: string;
            strategyTitle: string;
            strategyItems?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            conclusion: string;
            strategyImage: number | Media;
            imageDescription: string;
            processTitle: string;
            processDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'strategySection';
          }
        | {
            blockId: string;
            title: string;
            description: string;
            goals?:
              | {
                  title: string;
                  description: string;
                  isLight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'goalsSection';
          }
        | {
            blockId: string;
            title: string;
            subtitle: string;
            tasks?:
              | {
                  text: string;
                  isLight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'businessSection';
          }
        | {
            blockId: string;
            authorImage: number | Media;
            authorName: string;
            authorRole: string;
            authorDescription?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'authorSection';
          }
      )[]
    | null;
  showPortfolio?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  tags?: (number | Tag)[] | null;
  featuredImage: number | Media;
  content?:
    | (
        | {
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textContent';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageContent';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  featuredImage: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  name: string;
  email: string;
  message?: string | null;
  status?: ('Новая' | 'В работе' | 'Закрыта') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sections?:
    | T
    | {
        heroSection?:
          | T
          | {
              blockId?: T;
              subtitle?: T;
              description?: T;
              stamps?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              backgroundImage?: T;
              image?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              blockId?: T;
              subtitle?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        aboutProjectSection?:
          | T
          | {
              blockId?: T;
              projectTitle?: T;
              projectDescription?: T;
              client?: T;
              status?: T;
              caseTitle?: T;
              caseDescription?: T;
              id?: T;
              blockName?: T;
            };
        clientSection?:
          | T
          | {
              blockId?: T;
              contentTitle?: T;
              contentItems?:
                | T
                | {
                    text?: T;
                    anchorId?: T;
                    id?: T;
                  };
              clientImage?: T;
              clientImageDescription?: T;
              clientTitle?: T;
              clientSubtitle?: T;
              clientDescription?: T;
              layoutImage?: T;
              layoutImageDescription?: T;
              id?: T;
              blockName?: T;
            };
        strategySection?:
          | T
          | {
              blockId?: T;
              title?: T;
              description?: T;
              strategyTitle?: T;
              strategyItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              conclusion?: T;
              strategyImage?: T;
              imageDescription?: T;
              processTitle?: T;
              processDescription?: T;
              id?: T;
              blockName?: T;
            };
        goalsSection?:
          | T
          | {
              blockId?: T;
              title?: T;
              description?: T;
              goals?:
                | T
                | {
                    title?: T;
                    description?: T;
                    isLight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        businessSection?:
          | T
          | {
              blockId?: T;
              title?: T;
              subtitle?: T;
              tasks?:
                | T
                | {
                    text?: T;
                    isLight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        authorSection?:
          | T
          | {
              blockId?: T;
              authorImage?: T;
              authorName?: T;
              authorRole?: T;
              authorDescription?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
      };
  showPortfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  slug?: T;
  tags?: T;
  sections?:
    | T
    | {
        heroSection?:
          | T
          | {
              blockId?: T;
              subtitle?: T;
              description?: T;
              stamps?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              backgroundImage?: T;
              image?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              blockId?: T;
              subtitle?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        aboutProjectSection?:
          | T
          | {
              blockId?: T;
              projectTitle?: T;
              projectDescription?: T;
              client?: T;
              status?: T;
              caseTitle?: T;
              caseDescription?: T;
              id?: T;
              blockName?: T;
            };
        clientSection?:
          | T
          | {
              blockId?: T;
              contentTitle?: T;
              contentItems?:
                | T
                | {
                    text?: T;
                    anchorId?: T;
                    id?: T;
                  };
              clientImage?: T;
              clientImageDescription?: T;
              clientTitle?: T;
              clientSubtitle?: T;
              clientDescription?: T;
              layoutImage?: T;
              layoutImageDescription?: T;
              id?: T;
              blockName?: T;
            };
        strategySection?:
          | T
          | {
              blockId?: T;
              title?: T;
              description?: T;
              strategyTitle?: T;
              strategyItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              conclusion?: T;
              strategyImage?: T;
              imageDescription?: T;
              processTitle?: T;
              processDescription?: T;
              id?: T;
              blockName?: T;
            };
        goalsSection?:
          | T
          | {
              blockId?: T;
              title?: T;
              description?: T;
              goals?:
                | T
                | {
                    title?: T;
                    description?: T;
                    isLight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        businessSection?:
          | T
          | {
              blockId?: T;
              title?: T;
              subtitle?: T;
              tasks?:
                | T
                | {
                    text?: T;
                    isLight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        authorSection?:
          | T
          | {
              blockId?: T;
              authorImage?: T;
              authorName?: T;
              authorRole?: T;
              authorDescription?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
      };
  showPortfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tags?: T;
  featuredImage?: T;
  content?:
    | T
    | {
        textContent?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        imageContent?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  title?: string | null;
  featuredCases?:
    | {
        case: number | Case;
        id?: string | null;
      }[]
    | null;
  aboutCompanySection?: string | null;
  weCreateItems?:
    | {
        title: string;
        description: string;
        advantages?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        number?: string | null;
        gradient?: ('blue-gradient' | 'green-gradient' | 'red-gradient') | null;
        light?: boolean | null;
        id?: string | null;
      }[]
    | null;
  portfolioItems?:
    | {
        title: string;
        links?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  portfolioThemes?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  mobileAppItems?:
    | {
        title: string;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  highlightedCases?:
    | {
        title: string;
        description?: string | null;
        image: number | Media;
        date: string;
        themes?:
          | {
              theme?: string | null;
              id?: string | null;
            }[]
          | null;
        views?: number | null;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        type: string;
        list?:
          | {
              techName: string;
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq1 {
  id: number;
  title?: string | null;
  description?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title?: string | null;
  themesList?:
    | {
        themeName: string;
        id?: string | null;
      }[]
    | null;
  posts?:
    | {
        title: string;
        description: string;
        image: number | Media;
        date: string;
        views?: number | null;
        themes?:
          | {
              theme?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  featuredCases?:
    | T
    | {
        case?: T;
        id?: T;
      };
  aboutCompanySection?: T;
  weCreateItems?:
    | T
    | {
        title?: T;
        description?: T;
        advantages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        number?: T;
        gradient?: T;
        light?: T;
        id?: T;
      };
  portfolioItems?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  portfolioThemes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  mobileAppItems?:
    | T
    | {
        title?: T;
        image?: T;
        imageAlt?: T;
        id?: T;
      };
  highlightedCases?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        date?: T;
        themes?:
          | T
          | {
              theme?: T;
              id?: T;
            };
        views?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        type?: T;
        list?:
          | T
          | {
              techName?: T;
              logo?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  themesList?:
    | T
    | {
        themeName?: T;
        id?: T;
      };
  posts?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        date?: T;
        views?: T;
        themes?:
          | T
          | {
              theme?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}